import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SessionProviderWrapper } from "@/components/layout/SessionProviderWrapper";
import { HydrationProvider } from "@/components/layout/HydrationProvider";
import { Navbar } from "@/components/layout/Navbar";
import { CartDrawerProvider } from "@/components/layout/CartDrawerProvider";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="es">
            <body>
                <SessionProviderWrapper>
                    <HydrationProvider>
                        <CartDrawerProvider>
                            <Navbar />
                            <main>{children}</main>
                        </CartDrawerProvider>
                    </HydrationProvider>
                </SessionProviderWrapper>
            </body>
        </html>
    );
}
